### ISSUE TITLE
universal-env#isWeex is not work correctly

### ISSUE THREAD

**Issue by Z-Janp** [alibaba/bindingx#12]
`if (isWeex) {
    /**/
} else {
 return WebBinding.bind(options, callback)
}`

logcat : ReportException : Exception: TypeError: WebBinding.bind is not a function. 
**typeof callNative !== 'function'**

env: {
  weexSDK: 0.18.0-beta-3
  bindingx-core: 1.0.1
  android: 6
}

**Comment by Rowandjj** [comment]
You should install `weex-bindingx` by:

```
npm install weex-bindingx --save
```
and then you can import&use it:

```
import BindingX from weex-bindingx;
...
BindingX.bind();
```

**Comment by Rowandjj** [comment]
@Z-Janp well, so the problem is `universal-env#isWeex` return false ?

as far as I know, in the latest version of weex，`callNative` is moved，so you cannot use that to determine whether weex is exists or not. Instead you should use `WXEnvironment `.  

The newest version of `universal-env` has already solved the problem:

```
//https://github.com/alibaba/rax/blob/master/packages/universal-env/src/index.js
export const isWeex = typeof callNative === 'function' || typeof WXEnvironment === 'object';
```
So update `universal-env` should solve the problem. Or you can degrade your weex version.

ths:)

**Comment by Z-Janp** [comment]
Yes, that is what I want to express.
but, I found that weex-bindingx relies on universal-env.
And, I have upgraded universal-env. But they haven't pushed the latest code to the npm repository.
I'm just wondering why weex-bindingx depends on universal-env.
Your answer is helpful.
Thx u!!!

**Comment by Rowandjj** [comment]
@Z-Janp In fact `weex-bindingx` is not rely on universal-env at all.  

Because we have a web polyfill version of bindingx which can run on browser, however, `findDomNode` API is difference between weex and web. So you can see this function in our demos: 

```
function getEl(el) {
  return isWeex ? findDOMNode(el).ref : findDOMNode(el);
}
```
=====

As for your problem, there are some ways to go out:
1.  Use `universal-env#isWeb` variable to do the same thing.
2.  Implement `isWeex` yourself 
       ```
        let  isWeex = typeof callNative === 'function' || typeof WXEnvironment === 'object';
      ```
3. If you do not need to compatible with html5, just remove `isWeex`.

ths:)

**Comment by Rowandjj** [comment]
@Z-Janp umm, I found that too. The Rax team will figure that out later.

For now, use `isWeb` maybe the best option for you.

**Comment by Z-Janp** [comment]
ok, thx again!
